### ISSUE TITLE
https is not loading for revert_impersonate_user_url

### ISSUE THREAD

**Issue by synechron-ror** [rcook/user_impersonate2#10]
I have a application using HTTPS but when I am impersonating a user the (revert_impersonate_user_url) URL doesnt take https, Its always http. Am I missing anything or its not implemented ?

**Comment by rcook** [comment]
@synechron-ror: Good question. Let me investigate and get back to you.

**Comment by rcook** [comment]
Are you using `force_ssl`? Are you using a frontend server like Apache or Nginx?

**Comment by bhushangahire** [comment]
I am not using force_ssl but I have nginx as frontend server. I dont think that matters.

**Comment by bhushangahire** [comment]
As of now I am using below to check if request is SSL
      <% imp_url = request.ssl? ? impersonate_engine.revert_impersonate_user_url(protocol: 'https') : impersonate_engine.revert_impersonate_user_url %>

**Comment by rcook** [comment]
@bhushangahire: To be honest, I have not actively used this gem in about three years and I'm unlikely to be able to find much time to investigate this bug. However, I am happy to accept pull requests and publish updates to the gem as appropriate.

**Comment by mrhazel** [comment]
After spending an hour with this exact problem (nginx redirect, `force_ssl` off) and writing a similar check based on environment, this isn't a bug in user_impersonate2 but rather with the Rails URL helpers.  

change `impersonate_engine.revert_impersonate_user_url` to `impersonate_engine.revert_impersonate_user_path`.

**Comment by rcook** [comment]
Since this is not a bug in this package, I will close this issue. Thanks!
