### ISSUE TITLE
Inconsistency in Impersonate reverting process

### ISSUE THREAD

**Issue by manishrawat0212** [rcook/user_impersonate2#17]
Consider there are 3 users: X, Y and Z; and all these users have the permission to impersonate.

## Steps to replicate
- Login with `user X`.
- Impersonate `user Y`. (Now the staff user will be `X` and current user will be `Y`)
- Now without reverting the on going impersonate; start impersonating `user Z`. (This time the staff user will be `Y` and current user will be `Z`)
- Revert impersonate.

Impersonate will get reverted and you will be logged in as `user Y`.
Initially we started with `user X`, but after impersonating **twice** (without reverting the first impersonate), I became `user Y`.

## Possible enhancement
While a user is impersonating another user, during this period the user should not be able to start impersonating another user.
To impersonate another user, the user should first revert the ongoing impersonate.

If you consider this a possible enhancement, I can give a PR for this change.

**Comment by rcook** [comment]
@manishrawat0212 : Sorry for not having responded sooner. I have not been actively maintaining this package for quite some time. There seems to be some interest in other users taking over ownership, so you may see more activity here. I will close this issue for now. However, if you would like to contribute an enhancement, please go ahead and reopen it.

**Comment by Jerph** [comment]
This is a major issue as it makes it impossible to tell who the actual actor is after the nested impersonation. All it takes to resolve it is not updating `session[:staff_user_id]` if it was already set. That is, change...

```session[:staff_user_id] = current_staff.id```
... to ...
```session[:staff_user_id] ||= current_staff.id```

If you reopen I could send a pull request.
