### ISSUE TITLE
Anything holding off publishing 0.12.0?

### ISSUE THREAD

**Issue by adamaig** [rcook/user_impersonate2#22]
Hi! 

The latest version of the gem at https://rubygems.org/gems/user_impersonate2 is 0.11 which includes the usages of `before_filter` which break Rails 5.1. I'm wondering, is there is anything preventing the publishing of the 0.12.0 version of the gem?

**Comment by rcook** [comment]
I don't have time to do it, that's all. I recently added @julioalucero as a project owner (both on GitHub and RubyGems) so that he could do this. If you would like to be added as an owner, I would be happy to do that too. I just don't have the time to maintain this project any more.

**Comment by adamaig** [comment]
Sorry for the slow response. I'm happy to push it, but like you won't have time to maintain this.

**Comment by jeremybdk** [comment]
Hello @rcook,
We use this gem in production at Appaloosa.io so I am pretty sure that @benoittgt and me would be happy to help maintain it.

**Comment by rcook** [comment]
@jeremybdk: I have added you and @benoittgt as collaborators with push privileges on this repo.

**Comment by rcook** [comment]
@jeremybdk and @benoittgt: I will need your e-mail addresses to add you as owners to the gem at https://rubygems.org/ so you can publish new versions to the repository. Please contact me via my e-mail address in my commit history with this information so I can add you.

**Comment by rcook** [comment]
As a stopgap measure, I have published version 0.12.0 to https://rubygems.org/.

**Comment by rcook** [comment]
I'll close this issue since 0.12.0 has now been published. I will add the new owners as soon as I have their e-mail addresses.

**Comment by rcook** [comment]
I've transferred this project to a new "userimpersonate" organization at https://github.com/userimpersonate/ which makes sense if we're going to have multiple collaborators for it.
