### ISSUE TITLE
Using user_impersontate with rails models that manually set the table_name fails

### ISSUE THREAD

**Issue by kfranzen** [rcook/user_impersonate2#6]
The engine fails to determine the correct table_name for any model that has manually set the table_name.

The issue is with the #user_table method in the ImpersonateController:

    module UserImpersonate
      class ImpersonateController < ApplicationController
        ...

        def user_table
          user_class_name.tableize.tr('/', '_')
        end
        ...
      end
    end

I have run into this while migrating a Rails app to use engines. 

The original app had a model User that was used by Devise and UserImpersonate. Everything was good.

As part of the migration and refactoring the original model is now in a shared engine MyCommonEngine::User. 

If that was the only change then renaming the table would be an easy enough fix.

However, there are a couple of other engines that have models that inherit from MyCommonEngine::User to add engine specific functionality. 

To avoid issues we are explicitly setting the table_name for the class to the existing :user table:

    module MyCommonEngine
      class User < ActiveRecord::Base
        set.table_name :users
        ...
      end
    end

With that code the ImpersonateController#user_table method does not return the correct table name causing the queries for UserImpersonate to fail.

We have fixed the issue by changing #user_table to the following:

    def user_table
      user_class.table_name
    end

The ImpersonateController#user_class method is used to get the correct class then the classes table_name method is called to get the proper table_name. 

Everything works correctly with that one change.

This gem doesn't change much so I am happy to run with a forked version, but if this seems like a reasonable solution I can produce a pull request for the change when I have a few minutes.

**Comment by rcook** [comment]
Please submit a pull request!
